name: Storefront Build CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - name: Install pnpm
        run: npm install -g pnpm # Ensure pnpm is installed
      - name: Install dependencies
        run: pnpm install # Install dependencies using pnpm
      - name: Check lint
        run: pnpm lint:all
      - name: Create Build
        run: pnpm build:all
